Added LD_LIBRARY_PATH to the ExecutorEnv. This is need so that the nodes can find libjvm.so, or if the master has a different LD_LIBRARY_PATH then the nodes. Make sure to export LD_LIBRARY_PATH  that includes the path to libjvm.so in the nodes.
To Run:

USE_YARN=1 SPARK_YARN_VERSION=2.4.0 SPARK_HADOOP_VERSION=2.4.0 ./install-dev.sh
export YARN_CONF_DIR=<yarn_conf_dir>
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/ to/ libjvm.so/ on/ nodes/"
MASTER="yarn-client" ./sparkR


If LD_LIBRARY_PATH not properly set you will find the following error in the yarn logs

Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/lib/Rlibrary/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
Error: package ‘rJava’ could not be loaded
Execution halted